/*
 * Word Buddies offline support: every app file is cached on first visit so
 * the game works with no internet. The list below is generated by
 * tools/build-sw.js; VERSION changes whenever any file changes, which makes
 * phones fetch the new version.
 */
const VERSION = 'c5711f3ee6';
const CACHE = 'word-buddies-' + VERSION;
const ASSETS = [
  // ASSETS-START
  './',
  'index.html',
  'manifest.webmanifest',
  'css/app.css',
  'js/app.js',
  'js/audio.js',
  'js/progress.js',
  'js/storage.js',
  'js/words.js',
  'fonts/fredoka-latin.woff2',
  'img/icons/icon-180.png',
  'img/icons/icon-192.png',
  'img/icons/icon-512.png',
  'img/icons/icon-maskable-512.png',
  'img/stickers/butterfly.png',
  'img/stickers/chick.png',
  'img/stickers/crown.png',
  'img/stickers/cupcake.png',
  'img/stickers/dino.png',
  'img/stickers/dolphin.png',
  'img/stickers/elephant.png',
  'img/stickers/fire-truck.png',
  'img/stickers/flamingo.png',
  'img/stickers/fox.png',
  'img/stickers/frog.png',
  'img/stickers/helicopter.png',
  'img/stickers/ice-cream.png',
  'img/stickers/kite.png',
  'img/stickers/koala.png',
  'img/stickers/ladybug.png',
  'img/stickers/lion.png',
  'img/stickers/lollipop.png',
  'img/stickers/monkey.png',
  'img/stickers/octopus.png',
  'img/stickers/panda.png',
  'img/stickers/penguin.png',
  'img/stickers/planet.png',
  'img/stickers/rainbow.png',
  'img/stickers/rocket.png',
  'img/stickers/sloth.png',
  'img/stickers/snowman.png',
  'img/stickers/strawberry.png',
  'img/stickers/sunflower.png',
  'img/stickers/t-rex.png',
  'img/stickers/tiger.png',
  'img/stickers/tractor.png',
  'img/stickers/turtle.png',
  'img/stickers/unicorn.png',
  'img/stickers/watermelon.png',
  'img/stickers/whale.png',
  'img/ui/gift.png',
  'img/ui/house.png',
  'img/ui/party.png',
  'img/ui/picture.png',
  'img/ui/search.png',
  'img/ui/speaker.png',
  'img/ui/speaking.png',
  'img/ui/star.png',
  'img/ui/thumb.png',
  'img/words/all-done.png',
  'img/words/apple.png',
  'img/words/baby.png',
  'img/words/ball.png',
  'img/words/banana.png',
  'img/words/bath.png',
  'img/words/bed.png',
  'img/words/bird.png',
  'img/words/book.png',
  'img/words/bubbles.png',
  'img/words/bye-bye.png',
  'img/words/car.png',
  'img/words/cat.png',
  'img/words/cookie.png',
  'img/words/cow.png',
  'img/words/daddy.png',
  'img/words/dog.png',
  'img/words/down.png',
  'img/words/drink.png',
  'img/words/duck.png',
  'img/words/ears.png',
  'img/words/eat.png',
  'img/words/eyes.png',
  'img/words/fish.png',
  'img/words/go.png',
  'img/words/hat.png',
  'img/words/help.png',
  'img/words/hi.png',
  'img/words/hug.png',
  'img/words/juice.png',
  'img/words/milk.png',
  'img/words/mommy.png',
  'img/words/moon.png',
  'img/words/mouth.png',
  'img/words/no.png',
  'img/words/nose.png',
  'img/words/open.png',
  'img/words/pig.png',
  'img/words/please.png',
  'img/words/shoes.png',
  'img/words/sleep.png',
  'img/words/socks.png',
  'img/words/stop.png',
  'img/words/sun.png',
  'img/words/teddy.png',
  'img/words/uh-oh.png',
  'img/words/up.png',
  'img/words/water.png',
  'img/words/yes.png'
  // ASSETS-END
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('word-buddies-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
        }
        return res;
      }).catch(() => (req.mode === 'navigate' ? caches.match('index.html') : Response.error()));
    })
  );
});
